.\"-
.\" SPDX-License-Identifier: BSD-2-Clause-FreeBSD
.\"
.\" Copyright (c) 2015 University of Cambridge  All rights reserved.
.\" Copyright (c) 2015 Bjoern A. Zeeb  All rights reserved.
.\" Copyright (c) 2020 Denis Salopek  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.\" This software was developed by Stanford University and the University of
.\" Cambridge Computer Laboratory under National Science Foundation under Grant
.\" No. CNS-0855268, the University of Cambridge Computer Laboratory under EPSRC
.\" INTERNET Project EP/H040536/1 and by the University of Cambridge Computer
.\" Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"), as part of
.\" the DARPA MRC research programme.
.\"
.\" $FreeBSD$
.\"
.Dd July 25, 2020
.Dt SUME 4
.Os
.Sh NAME
.Nm sume
.Nd "NetFPGA SUME 4x10Gb Ethernet driver"
.Sh SYNOPSIS
To compile this driver into the kernel, place the following lines in your
kernel configuration file:
.Bd -ragged -offset indent
.Cd "device sume"
.Ed
.Pp
Alternatively, to load the driver as a module at boot time, place the following
line in
.Xr loader.conf 5 :
.Bd -literal -offset indent
if_sume_load="YES"
.Ed
.Sh DESCRIPTION
The
.Nm
driver provides support for NetFPGA SUME Virtex-7 FPGA Development Board with
the reference NIC bitstream loaded onto it.
The HDL design for the reference NIC project uses the RIFFA based DMA engine to
communicate with the host machine over PCIe.
Every packet is transmitted to / from the board via one DMA transaction, taking
up to two or three interrupts per one transaction which yields in low
performance.

There is no support for Jumbo frames as the hardware is capable of dealing only
with frames with maximum size of 1514 bytes.

The hardware provides no checksums and offers no other offloading.
.Sh BUGS
Pre-built bitstream from Cambridge may not work correctly - at higher RX packet
rates, the newly incoming packets would overwrite the ones in some internal
FIFO so the packets would come out of the board scrambled until physical reset
of the board.

There is also a strange behaviour in the TX path: when sending "small" packets,
TX works as it should, but when sending packets above some size limit right
after loading the driver, SUME doesn't send the TX_DONE interrupt and refuses
to send packets until the driver is reloaded / board is reset.
This would mean that the driver would get stuck in a non-IDLE TX state but a
watchdog-like function is implemented in the driver to check whether the
non-IDLE state lasts more then 3 seconds and it resets the board automatically.
For more details, visit the NetFPGA SUME project site.
.Sh SEE ALSO
.Xr arp 4 ,
.Xr ifconfig 8 ,
.Xr netgraph 4 ,
.Xr netintro 4 ,
.Xr ng_ether 4 ,
.Xr vlan 4
.Sh AUTHOR
The Linux NetFPGA SUME driver was originally written by Bjoern A. Zeeb.
The FreeBSD version is written by Denis Salopek as a GSoC project.
More information about the project can be found here:
.Pa https://wiki.freebsd.org/SummerOfCode2020Projects/NetFPGA_SUME_Driver
