.\" Manpage for NetFPGA SUME device driver.
.\" Contact denissal@freebsd.org to correct errors or typos.
.Dd July 25, 2020
.Dt SUME 4
.Os
.Sh NAME
.Nm sume
.Nd "NetFPGA SUME 4x10Gb Ethernet driver"
.Sh SYNOPSIS
To compile this driver into the kernel,
place the following lines in your
kernel configuration file:
.Bd -ragged -offset indent
.Cd "device sume"
.Ed
.Pp
Alternatively, to load the driver as a
module at boot time, place the following line in
.Xr loader.conf 5 :
.Bd -literal -offset indent
if_sume_load="YES"
.Ed
.Sh DESCRIPTION
The
.Nm
driver provides support for NetFPGA SUME Virtex-7 FPGA Development Board with
the reference NIC bitstream loaded onto it. The HDL design for the reference
NIC project uses the RIFFA based DMA engine to communicate with the host
machine over PCIe. Every packet is transmitted to / from the board via one DMA
transaction, taking two or three interrupts per one transaction which yields in
low performance.

There is no support for Jumbo frames as the hardware is capable of dealing only
with frames with maximum size of 1514 bytes.

The hardware provides no checksums and offers no other offloading.
.Sh PARAMETERS AND OPTIONS
The default (and maximum) number of created interfaces is 4. This can be
configured at load time with the kernel environment variable sume.nports:
.Dl # kenv sume.nports=4
.Sh SEE ALSO
.Xr arp 4 ,
.Xr ifconfig 8 ,
.Xr netgraph 4 ,
.Xr netintro 4 ,
.Xr ng_ether 4 ,
.Xr vlan 4
.Sh AUTHOR
The original Linux NetFPGA SUME driver was originally written by Bjoern A.
Zeeb. The FreeBSD version is written by Denis Salopek as a GSoC project. More
information about the project can be found here:
.Pa https://wiki.freebsd.org/SummerOfCode2020Projects/NetFPGA_SUME_Driver
